---
kind: pipeline
type: docker
name: push-latest
steps:
- name: build-and-push
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-release
steps:
- name: build-and-push-tag
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_TAG##v} # strips v from the tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag
---
kind: pipeline
type: docker
name: dry-run
steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    dry_run: true
trigger:
  event:
  - pull_request
---
kind: secret
name: docker_username
data: iJkwy3uXBMx2C0C3fnxBqneTbTIFJCWjJ1wnkROX06AQkxYfN/Tr0A==
---
kind: secret
name: docker_password
data: 2AZUlYntJUF5CJH2zjokcF1GJKbT/suslhgl51cJOrKwbAvjJgCDApuQncuuJFJWHHsU0Be9qFI9H5QShA1sZA==
---
kind: signature
hmac: e8c07d942e0b3f65792093c887640b1a37702a33b0512bf88dfcb4670da824f6

...
