---
kind: pipeline
type: docker
name: push-latest
steps:
- name: build-and-push
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-release
steps:
- name: build-and-push-tag
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    tags: ${DRONE_TAG##v} # strips v from the tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag
---
kind: pipeline
type: docker
name: dry-run
steps:
- name: dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO}
    dry_run: true
trigger:
  event:
  - pull_request
---
kind: secret
name: docker_username
data: iJkwy3uXBMx2C0C3fnxBqneTbTIFJCWjJ1wnkROX06AQkxYfN/Tr0A==
---
kind: secret
name: docker_password
data: 2AZUlYntJUF5CJH2zjokcF1GJKbT/suslhgl51cJOrKwbAvjJgCDApuQncuuJFJWHHsU0Be9qFI9H5QShA1sZA==
---
kind: secret
name: docker_username
data: Ius0xCMKP2JMzYtIRr8EZ1lUjjWn657jWAAR2SF7HK86sZsyunnpvg==
---
kind: secret
name: docker_password
data: /Ktq3Q48/uhQ+WxfQkYhivplJcU9bvV0zBDU4bZ0TtnDw/ik42QKPDXggjU+lFQYn13VEgy3L6T+nHqTVrEgDg==
---
kind: signature
hmac: fc3eead92d9e0a25d32087880323b422dd6169a9c1ef119e415b2052f1b5688d

...
